### PR TITLE
refactor some code to remove warnings

### PR DESCRIPTION
**Pull request by TheComputerM**
Few to no warnings while development or building

Before:
image

After:
image

### CODE REVIEW

**Comment by TheComputerM** [comment]
Shall I update the package.json to use newer packages?

**Comment by sidharth-anand** [comment]
Can you fix the conflicts in the css? Everything else LGTM

**Comment by TheComputerM** [comment]
Done, apologies for the wait

**Comment by sidharth-anand** [comment]
@all-contributors please add @TheComputerM for code

**Pull request merged**
